ITZipProject/itzip_back

- .gitignore
- src/main/java/darkoverload/itzip/global/config/exception/exception/RestApiException.java
- src/main/java/darkoverload/itzip/global/config/exception/exceptionCode/CommonExceptionCode.java
- src/main/java/darkoverload/itzip/global/config/exception/exceptionCode/ExceptionCode.java
- src/main/java/darkoverload/itzip/global/config/exception/handler/ExceptionHandlerUtil.java
- src/main/java/darkoverload/itzip/global/config/exception/handler/GlobalExceptionHandler.java
- src/main/java/darkoverload/itzip/global/config/exception/response/ExceptionResponse.java
- src/test/java/darkoverload/itzip/global/config/exception/GlobalExceptionHandlerTest.java
- src/test/java/darkoverload/itzip/global/config/exception/TestController.java
전역 예외 처리 기능 추가
자세한 내용은 commit확인
> 🔀	브랜치 합병 : Feature/global exception

- src/main/java/darkoverload/itzip/global/config/security/SecurityConfig.java
- src/main/java/darkoverload/itzip/security/SecurityConfig.java
> 🔀 브랜치 합병 : Feature/security

- build.gradle
- src/main/java/darkoverload/itzip/ItzipApplication.java
- src/main/java/darkoverload/itzip/global/config/response/handler/GlobalExceptionHandler.java
- src/main/java/darkoverload/itzip/global/config/security/SecurityConfig.java
- src/main/java/darkoverload/itzip/global/entity/AuditingFields.java
- src/main/java/darkoverload/itzip/jwt/entity/Token.java
- src/main/java/darkoverload/itzip/jwt/exception/CustomJwtException.java
- src/main/java/darkoverload/itzip/jwt/exception/TokenExceptionCode.java
- src/main/java/darkoverload/itzip/jwt/filter/TokenAuthenticationFilter.java
- src/main/java/darkoverload/itzip/jwt/infrastructure/CustomUserDetails.java
- src/main/java/darkoverload/itzip/jwt/infrastructure/JwtAuthenticationToken.java
- src/main/java/darkoverload/itzip/jwt/repository/TokenRepository.java
- src/main/java/darkoverload/itzip/jwt/service/CustomUserDetailsService.java
- src/main/java/darkoverload/itzip/jwt/service/TokenService.java
- src/main/java/darkoverload/itzip/jwt/util/JwtTokenizer.java
- src/main/java/darkoverload/itzip/user/controller/UserController.java
- src/main/java/darkoverload/itzip/user/dto/UserLoginDto.java
- src/main/java/darkoverload/itzip/user/dto/UserLoginResponseDto.java
- src/main/java/darkoverload/itzip/user/entity/Authority.java
- src/main/java/darkoverload/itzip/user/entity/User.java
- src/main/java/darkoverload/itzip/user/repository/UserRepository.java
- src/main/java/darkoverload/itzip/user/sevice/UserService.java
- src/main/resources/application-local.yml
1. JWT 기본 세팅(의존성 추가, yml 구성 파일 수정)
2. 로그인(JWT 발급) 기능
3. JWT refresh token으로 access token 재발급 기능
4. 로그아웃(JWT 삭제) 기능
Resolves: #11
> ✨ feat: JWT 기본 세팅 및 로그인 기능 구현

- src/main/java/darkoverload/itzip/global/config/response/code/CommonExceptionCode.java
- src/main/java/darkoverload/itzip/global/config/response/code/CommonResponseCode.java
- src/main/java/darkoverload/itzip/global/config/response/code/ResponseCode.java
- src/main/java/darkoverload/itzip/global/config/response/exception/RestApiException.java
- src/main/java/darkoverload/itzip/global/config/response/handler/GlobalExceptionHandler.java
- src/main/java/darkoverload/itzip/global/config/response/handler/GlobalSuccessHandler.java
- src/main/java/darkoverload/itzip/global/config/response/handler/Util/ExceptionHandlerUtil.java
- src/main/java/darkoverload/itzip/global/config/response/handler/Util/ResponseHandlerUtil.java
- src/main/java/darkoverload/itzip/global/config/response/response/ExceptionResponse.java
- src/main/java/darkoverload/itzip/global/config/response/response/SuccessResponse.java
- src/main/java/darkoverload/itzip/global/config/security/SecurityConfig.java
- src/main/java/darkoverload/itzip/global/config/swagger/ExceptionCodeAnnotations.java
- src/main/java/darkoverload/itzip/global/config/swagger/ResponseCodeAnnotation.java
- src/main/java/darkoverload/itzip/global/config/swagger/SwaggerConfig.java
- src/main/java/darkoverload/itzip/sample/swagger/SwaggerUIExampleController.java
1. swagger 문서 기본 UI 및 security swagger문서화를 위한 추가
2. 응답코드 주석 추가 및 응답 코드에 CommonResponseCode에 있는 다양한 코드를 사용하도록 수정
> 🔀	브랜치 합병 : Feature/swagger

- src/main/java/darkoverload/itzip/global/config/swagger/SwaggerConfig.java
이런식으로 여러 같은 코드 에러가 들어와도 나타낼수 있도록 만들었습니다.
> 🐛	버그 수정 : swagger 에러코드가 같아도 다른 에러로 swagger에 적히도록 수정

- src/main/java/darkoverload/itzip/feature/school/code/EstType.java
- src/main/java/darkoverload/itzip/feature/school/code/RegionType.java
- src/main/java/darkoverload/itzip/feature/school/code/SchoolType.java
- src/main/java/darkoverload/itzip/feature/school/domain/School.java
- src/main/java/darkoverload/itzip/feature/school/scheduler/SchoolScheduler.java
- src/main/java/darkoverload/itzip/feature/school/service/SchoolConnectServiceImpl.java
- src/main/java/darkoverload/itzip/feature/school/util/SchoolJsonUtil.java
> 💡 Docs : 주석 추가 완료

- src/main/java/darkoverload/itzip/feature/school/controller/SchoolController.java
- src/main/java/darkoverload/itzip/feature/school/controller/response/SearchResponse.java
- src/main/java/darkoverload/itzip/feature/school/repository/CustomSchoolRepository.java
- src/main/java/darkoverload/itzip/feature/school/repository/CustomSchoolRepositoryImpl.java
- src/main/java/darkoverload/itzip/feature/school/repository/SchoolRepository.java
- src/main/java/darkoverload/itzip/feature/school/service/SchoolService.java
- src/main/java/darkoverload/itzip/feature/school/service/SchoolServiceImpl.java
- src/main/java/darkoverload/itzip/feature/school/service/connect/SchoolConnectService.java
- src/main/java/darkoverload/itzip/feature/school/service/connect/SchoolConnectServiceImpl.java
- src/test/java/darkoverload/itzip/feature/school/repository/SchoolRepositoryTest.java
> ✨ 새기능 : 학교 정보 API 조회 코드 추가 

- src/main/java/darkoverload/itzip/feature/jwt/domain/Token.java
- src/main/java/darkoverload/itzip/feature/jwt/repository/TokenRepository.java
- src/main/java/darkoverload/itzip/feature/jwt/service/TokenServiceImpl.java
> 🚑 긴급 수정 - 로그인 시 token 데이터가 갱신되지 않는 오류 수정

- src/main/java/darkoverload/itzip/feature/csQuiz/controller/CsQuizController.java
- src/main/java/darkoverload/itzip/feature/csQuiz/controller/request/QuizCreatedRequest.java
- src/main/java/darkoverload/itzip/feature/csQuiz/service/QuizService.java
- src/main/java/darkoverload/itzip/feature/csQuiz/service/QuizServiceImpl.java
- src/main/java/darkoverload/itzip/feature/csQuiz/service/sub/quiz/CreateQuiz.java
- src/main/java/darkoverload/itzip/feature/csQuiz/service/sub/quiz/CreateQuizImpl.java
- src/main/java/darkoverload/itzip/feature/csQuiz/util/QuizMapper.java
- src/main/java/darkoverload/itzip/global/config/response/code/CommonExceptionCode.java
- src/main/java/darkoverload/itzip/global/config/security/SecurityConfig.java
퀴즈를 생설할때 mongo는 트렌젝션이 안됨
지금은 mongodb쓸때 mongo에만 기록하기 때문에 트렌젝션 문제가 없을 것같아설 일단은 exception처리만 해두었음
> ✨	새 기능 : 퀴즈 생성 기능 추가

- src/main/java/darkoverload/itzip/feature/school/repository/SchoolRepository.java
- src/main/java/darkoverload/itzip/feature/school/repository/custom/CustomSchoolRepository.java
- src/main/java/darkoverload/itzip/feature/school/repository/custom/CustomSchoolRepositoryImpl.java
- src/main/java/darkoverload/itzip/feature/school/service/SchoolServiceImpl.java
- src/test/java/darkoverload/itzip/feature/school/SchoolInsertConnect.java
- src/test/resources/application-test.yml
1. service 쿼리 -> custom repository 코드로 이동
2. @deprecated 주석 코드 추가
> 🛠️ 리팩토링 : 코드 구조 개선

- src/main/resources/static/swagger-ui/index.html
지금 쿼리를 사용해서 객체를 선택하고 있는데
아직 logout버튼 Authorize 버튼을 정확히 걸지는 못했습니다.
일단 url "/api/v3/api-docs" 수정을 올리기 위해서 push했습니다.
> 🎨	코드의 구조/형태 개선 : fuction 변환

- src/main/java/darkoverload/itzip/feature/csQuiz/controller/CsQuizController.java
- src/main/java/darkoverload/itzip/feature/csQuiz/controller/CsQuizzesController.java
- src/main/java/darkoverload/itzip/feature/csQuiz/entity/QuizDocument.java
- src/main/java/darkoverload/itzip/feature/csQuiz/repository/quiz/custom/CustomQuizRepository.java
- src/main/java/darkoverload/itzip/feature/csQuiz/repository/quiz/custom/CustomQuizRepositoryImpl.java
- src/main/java/darkoverload/itzip/feature/csQuiz/service/QuizServiceImpl.java
- src/main/java/darkoverload/itzip/feature/csQuiz/service/sub/quizCategory/FindQuizCategoryImpl.java
- src/main/java/darkoverload/itzip/feature/csQuiz/service/sub/quizzes/FindQiuzQuery.java
- src/main/java/darkoverload/itzip/feature/csQuiz/service/sub/quizzes/FindQuizQuerytImpl.java
> 📝	문서 추가 : csQuiz swagger 설명 추가

- src/main/java/darkoverload/itzip/feature/csQuiz/controller/CsQuizController.java
- src/main/java/darkoverload/itzip/feature/csQuiz/controller/CsQuizzesController.java
- src/main/java/darkoverload/itzip/feature/csQuiz/controller/request/QuizQueryRequest.java
- src/main/java/darkoverload/itzip/feature/csQuiz/entity/SortBy.java
- src/main/java/darkoverload/itzip/feature/csQuiz/repository/quiz/custom/CustomQuizRepositoryImpl.java
- src/main/java/darkoverload/itzip/feature/csQuiz/service/QuizServiceImpl.java
- src/main/java/darkoverload/itzip/feature/csQuiz/service/sub/quizCategory/FindQuizCategory.java
- src/main/java/darkoverload/itzip/feature/csQuiz/service/sub/quizCategory/FindQuizCategoryImpl.java
- src/main/java/darkoverload/itzip/feature/csQuiz/service/sub/quizzes/FindQiuzQuery.java
- src/main/java/darkoverload/itzip/feature/csQuiz/service/sub/quizzes/FindQuizQuerytImpl.java
- src/main/java/darkoverload/itzip/global/config/swagger/SwaggerConfig.java
- src/main/java/darkoverload/itzip/global/config/swagger/SwaggerRequestBody.java
커스텀 SwaggerRequsetBody를 추가했습니다.
> 🚑	긴급 수정 : swagger RequestBody와 annotation body문제 해결 수정

- src/main/java/darkoverload/itzip/ItzipApplication.java
- src/main/java/darkoverload/itzip/global/config/mongo/MongoConfig.java
- MongoDB 감사 클래스에 필요한 매핑 관련 MongoMappingContext 빈을 생성하지 않은 치명적인 오류 수정
```java
@Configuration
@EnableMongoAuditing <- ItzipApplication.java에서 MongoConfig 로 위치 변경
public class MongoConfig {
// 기존 코드 영역...
@Bean
public MongoMappingContext mongoMappingContext() {
MongoMappingContext mappingContext = new MongoMappingContext();
return mappingContext;
}
}
```
Ref : #35, #46
> 🚑 긴급 수정 : MongoDB 감사 클래스 매핑 오류 수정

- build.gradle
- src/main/resources/logback-spring.xml
1. db 쿼리 발생 시 로깅
2. 에러 발생 시 로깅
logstash 설정은 아래와 같이 수정했습니다.
```conf
input {
beats {
port => 5044
}
tcp {
port => 50000
codec => json_lines # JSON 라인 형식으로 수신된 데이터 처리
}
}
filter {
if [logger_name] == "org.hibernate.SQL" {
mutate {
add_field => { "index_name" => "springboot-logs-sql-%{+YYYY.MM.dd}" } # SQL 로그를 위한 인덱스 이름 생성
}
} 
else if [level] == "ERROR" {
mutate {
add_field => { "index_name" => "springboot-logs-error-%{+YYYY.MM.dd}" } # 에러 로그를 위한 인덱스 이름 생성
}
}
}
output {
elasticsearch {
hosts => ["elasticsearch:9200"]
user => "elastic"
password => "${LOGSTASH_INTERNAL_PASSWORD}"
index => "%{index_name}" # 필터 단계에서 생성된 인덱스 이름을 사용하여 동적 인덱싱
}
stdout {
codec => json_lines # JSON 라인 형식으로 로그 출력
}
}
```
Resolves: #80
> ✨ 새 기능 : 로그 시각화 모니터링 기능

- src/main/java/darkoverload/itzip/feature/user/controller/UserController.java
- src/main/java/darkoverload/itzip/feature/user/controller/request/AuthEmailCheckRequest.java
- src/main/java/darkoverload/itzip/feature/user/controller/request/AuthEmailSendRequest.java
- src/main/java/darkoverload/itzip/feature/user/controller/request/DuplicateEmailRequest.java
- src/main/java/darkoverload/itzip/feature/user/service/UserService.java
- src/main/java/darkoverload/itzip/feature/user/service/UserServiceImpl.java
- src/main/java/darkoverload/itzip/global/config/security/SecurityConfig.java
> ✨ 새 기능: 이메일 중복 체크 기능

- src/main/java/darkoverload/itzip/feature/user/controller/UserController.java
- src/main/java/darkoverload/itzip/feature/user/service/UserService.java
- src/main/java/darkoverload/itzip/feature/user/service/UserServiceImpl.java
컨트롤러에서 비즈니스 로직을 최소화하도록 리팩토링
Resolves: #89
> 🛠️ 리팩토링 : 회원 기능 전체 코드

- src/main/java/darkoverload/itzip/feature/user/controller/UserController.java
- src/main/java/darkoverload/itzip/feature/user/controller/request/AuthEmailCheckRequest.java
- src/main/java/darkoverload/itzip/feature/user/controller/request/UserJoinRequest.java
- src/main/java/darkoverload/itzip/feature/user/controller/request/UserLoginRequest.java
swagger 기능이 업데이트 됨에 따른 user swagger 최신화 작업
Resolves: #86
> 📖 문서 수정 : user swagger 최신화

- src/main/java/darkoverload/itzip/feature/tech/controller/TechController.java
- src/main/java/darkoverload/itzip/feature/tech/controller/response/GetTechResponse.java
- src/main/java/darkoverload/itzip/feature/tech/domain/Tech.java
- src/main/java/darkoverload/itzip/feature/tech/entity/TechEntity.java
- src/main/java/darkoverload/itzip/feature/tech/repository/TechRepository.java
- src/main/java/darkoverload/itzip/feature/tech/service/TechService.java
- src/main/java/darkoverload/itzip/feature/tech/service/TechServiceImpl.java
- src/main/java/darkoverload/itzip/global/config/security/SecurityConfig.java
- 단순 조회 로직이므로 테스트 코드는 구현 안하겠습니다.
> ✨ 새 기능 :  기술 정보 조회 API 구현 완료

- src/main/java/darkoverload/itzip/feature/job/controller/JobInfoController.java
- src/main/java/darkoverload/itzip/feature/job/controller/request/JobInfoScrapRequest.java
- src/main/java/darkoverload/itzip/feature/job/controller/response/JobInfoSearchResponse.java
- src/main/java/darkoverload/itzip/feature/job/domain/JobInfo.java
- src/main/java/darkoverload/itzip/feature/job/domain/JobInfoScrap.java
- src/main/java/darkoverload/itzip/feature/job/entity/JobInfoEntity.java
- src/main/java/darkoverload/itzip/feature/job/entity/JobInfoScrapEntity.java
- src/main/java/darkoverload/itzip/feature/job/repository/JobInfoRepository.java
- src/main/java/darkoverload/itzip/feature/job/repository/JobInfoScrapRepository.java
- src/main/java/darkoverload/itzip/feature/job/repository/custom/CustomJobInfoRepositoryImpl.java
- src/main/java/darkoverload/itzip/feature/job/repository/custom/CustomJobInfoScrapRepository.java
- src/main/java/darkoverload/itzip/feature/job/repository/custom/CustomJobInfoScrapRepositoryImpl.java
- src/main/java/darkoverload/itzip/feature/job/scheduler/JobInfoScheduler.java
- src/main/java/darkoverload/itzip/feature/job/service/JobInfoService.java
- src/main/java/darkoverload/itzip/feature/job/service/JobInfoServiceImpl.java
- src/main/java/darkoverload/itzip/global/config/response/code/CommonExceptionCode.java
- src/main/java/darkoverload/itzip/global/config/security/SecurityConfig.java
- src/test/java/darkoverload/itzip/feature/job/repository/JobInfoRepositoryTest.java
- src/test/java/darkoverload/itzip/feature/job/service/connect/JobInfoConnectServiceTest.java
- 테스트 코드, 조회 정렬 조건 추가 후 채용공고 스크랩 기능을 Redis 캐싱을 이용하여 조금 더 고도화 할 예정입니다. 
jmeter를 사용하여 현재 성능과 Redis 캐싱을 사용하여 조금 더 빠른 것을 적용할 것입니다.
> ✨ 새 기능 : 채용공고 스크랩 기능 추가

- src/main/java/darkoverload/itzip/feature/user/controller/MypageController.java
- src/main/java/darkoverload/itzip/feature/user/controller/UserController.java
- src/main/java/darkoverload/itzip/feature/user/service/MypageService.java
- src/main/java/darkoverload/itzip/feature/user/service/MypageServiceImpl.java
- src/main/java/darkoverload/itzip/feature/user/service/UserService.java
- src/main/java/darkoverload/itzip/feature/user/service/UserServiceImpl.java
- src/main/java/darkoverload/itzip/global/config/response/code/CommonExceptionCode.java
회원정보 수정 페이지에서 사용할 수 있는 닉네임 중복 체크 기능입니다.
Resolves: #93
Ref: #109
> ✨ 새 기능 : 닉네임 중복 체크 기능

- src/main/java/darkoverload/itzip/feature/image/controller/ImageController.java
> 💩 똥 싼 코드 : 스웨거 멀티 파일 추가

- src/main/java/darkoverload/itzip/feature/user/controller/UserController.java
- src/main/java/darkoverload/itzip/feature/user/service/UserService.java
- src/main/java/darkoverload/itzip/feature/user/service/UserServiceImpl.java
1. 회원가입 테스트를 위한 임시 회원 삭제 기능
Resolved: #119
> ✨ 새 기능 : 임시 회원 삭제 기능

- src/main/java/darkoverload/itzip/feature/user/service/UserServiceImpl.java
- src/main/java/darkoverload/itzip/feature/user/service/VerificationService.java
- src/main/java/darkoverload/itzip/feature/user/service/VerificationServiceImpl.java
1. 필드값 검증 로직 추가
2. 이메일 인증 후 redis에 저장된 이메일 인증번호 삭제 로직 추가
Resolves: #145
> 🐛 오류 수정 - 회원가입 비즈니스 로직 중 누락된 로직 추가

- src/main/java/darkoverload/itzip/feature/user/controller/MypageController.java
- src/main/java/darkoverload/itzip/feature/user/controller/UserController.java
- src/main/java/darkoverload/itzip/feature/user/service/MypageService.java
- src/main/java/darkoverload/itzip/feature/user/service/MypageServiceImpl.java
- src/main/java/darkoverload/itzip/feature/user/service/UserService.java
- src/main/java/darkoverload/itzip/feature/user/service/UserServiceImpl.java
1. User 기능 응답 문자열 리턴으로 변경 
2. Mypage 기능 응답 문자열 리턴으로 변경 
Resolves: #112
> 🛠️ 리팩토링 : 회원 관련 기능 ResponseEntity 응답 문자열 리턴으로 변경 

- src/main/java/darkoverload/itzip/feature/user/controller/MypageController.java
- src/main/java/darkoverload/itzip/feature/user/controller/UserController.java
- src/main/java/darkoverload/itzip/feature/user/controller/request/ChangePasswordRequest.java
- src/main/java/darkoverload/itzip/feature/user/controller/request/UserJoinRequest.java
- src/main/java/darkoverload/itzip/feature/user/controller/request/UserLoginRequest.java
- src/main/java/darkoverload/itzip/feature/user/service/MypageService.java
- src/main/java/darkoverload/itzip/feature/user/service/MypageServiceImpl.java
- src/main/java/darkoverload/itzip/feature/user/service/UserService.java
- src/main/java/darkoverload/itzip/feature/user/service/UserServiceImpl.java
- src/main/java/darkoverload/itzip/global/config/response/handler/GlobalExceptionHandler.java
1. @RequestParam validation 공통 예외처리 추가
2. UserController 파라미터 validation 예외처리 방식 변경
3. MypageController 파라미터 validation 예외처리 방식 변경
> 🛠️ 리팩토링 : 회원 기능 파라미터 validation 예외처리 방식 변경 #109

- src/test/java/darkoverload/itzip/feature/algorithm/service/problem/FindProblemsByTagAndUserServiceTest.java
- src/test/java/darkoverload/itzip/feature/algorithm/service/problem/FindProblemsByUserServiceTest.java
- src/test/java/darkoverload/itzip/feature/algorithm/service/problem/SaveProblemsServiceTest.java
- src/test/java/darkoverload/itzip/feature/algorithm/service/tag/FindAllTagsServiceImplTest.java
- src/test/java/darkoverload/itzip/feature/algorithm/service/tag/SaveTagsServiceTest.java
- src/test/java/darkoverload/itzip/feature/algorithm/service/user/FindUserSolvedProfileServiceImplTest.java
- src/test/java/darkoverload/itzip/feature/algorithm/service/user/SaveUserSolvedProfileServiceImplTest.java
- src/test/java/darkoverload/itzip/feature/algorithm/service/user/UpdateUserSolvedProfileAndProblemServiceImplTest.java
MockitoExtension을 사용해서 작성했습니다.
given when then 방식입니다.
save 메서드들은 void를 어떻게 변경할지 고민중이라 Todo로 남겨뒀습니다.
> ✅	테스트 추가 : 알고리즘 테스트 코드 구현

- src/main/java/darkoverload/itzip/feature/csQuiz/controller/response/QuizDetailResponse.java
- src/main/java/darkoverload/itzip/feature/csQuiz/entity/QuizDocument.java
- src/main/java/darkoverload/itzip/feature/csQuiz/service/sub/quizzes/FindQuizQuerytImpl.java
- src/main/java/darkoverload/itzip/feature/csQuiz/util/QuizMapper.java
- src/main/resources/sql/quiz/data/Data_quizzes.json
cs퀴즈 문제 시간순 정렬을 위해 시간 추가 및 데이터 변경
MongoAuditingFields를 상속받아서 사용했음
> ✨	새 기능 : 문제 생성 및 수정 시간 추가

- src/main/java/darkoverload/itzip/feature/algorithm/service/user/UpdateUserSolvedProfileAndProblemServiceImpl.java
- src/main/java/darkoverload/itzip/feature/algorithm/util/SaveSolvedUser.java
- src/main/java/darkoverload/itzip/feature/csQuiz/controller/CsQuizzesController.java
- src/main/java/darkoverload/itzip/feature/csQuiz/controller/request/QuizQueryRequest.java
- src/main/java/darkoverload/itzip/feature/csQuiz/entity/QuizUserSolvedMapping.java
- src/main/java/darkoverload/itzip/feature/csQuiz/service/sub/quiz/CheckAnswerImpl.java
- src/main/java/darkoverload/itzip/feature/csQuiz/service/sub/quiz/GivenPointToQuizImpl.java
- src/main/java/darkoverload/itzip/feature/csQuiz/service/sub/quizzes/FindQuizQuerytImpl.java
- src/main/java/darkoverload/itzip/feature/csQuiz/util/QuizMapper.java
1.  solved.ac user 사진 저장시 415 에러가 생기는 것 처리
2.  solved.ac user 프로필이 적용 되었는지 확인하는 api
3.  기술퀴즈 문제 풀고 정답 맞췄을때 userQuizStatus가 solved로 변하지 않는 버그
> 🐛 오류 수정 : 기술퀴즈 및 solved.ac 프로필 버그 수정

- src/main/java/darkoverload/itzip/feature/csQuiz/controller/CsQuizzesController.java
- src/main/java/darkoverload/itzip/feature/csQuiz/controller/request/QuizQueryRequest.java
- src/main/java/darkoverload/itzip/feature/csQuiz/service/QuizServiceImpl.java
- src/main/java/darkoverload/itzip/feature/csQuiz/service/sub/quizzes/FindQiuzQuery.java
- src/main/java/darkoverload/itzip/feature/csQuiz/service/sub/quizzes/FindQuizQuerytImpl.java
- src/main/resources/logback-spring.xml
1. 사용자가 인증하지 않아도 csQuiz에 접근할 수 있도록 수정
2. console창에 log가 찍힐 때 색이 생기도록 추가
> ♻️ Fix/cs quiz no auth

- src/main/java/darkoverload/itzip/feature/techinfo/controller/blog/request/BlogUpdateIntroRequest.java
- src/main/java/darkoverload/itzip/feature/techinfo/controller/post/request/PostCommentUpdateRequest.java
- src/main/java/darkoverload/itzip/feature/techinfo/domain/blog/BlogPostTimeline.java
- src/main/java/darkoverload/itzip/feature/techinfo/domain/comment/Comment.java
- src/main/java/darkoverload/itzip/feature/techinfo/domain/comment/CommentDetails.java
- src/main/java/darkoverload/itzip/feature/techinfo/domain/post/Post.java
- src/test/java/darkoverload/itzip/feature/techinfo/mock/PostMockData.java
각 코드마다 불필요한 개행을 삭제해 일관성을 개선했습니다 :)
> 🎨 코드의 형태 개선 : 불필요한 개행 삭제로 가독성과 일관성 개선

- src/main/java/darkoverload/itzip/feature/user/controller/request/UserJoinRequest.java
> 🛠️ 리팩토링 : User 기능 파라미터 camel case로 통일

- src/main/java/darkoverload/itzip/feature/user/service/UserServiceImpl.java
- src/main/resources/sql/techinfo/techinfo_blogs.sql
- src/test/java/darkoverload/itzip/feature/techinfo/repository/post/PostReadRepositoryTest.java
- **변경 내용**:
- `UserEntity`를 저장한 후 반환된 영속 상태의 객체를 사용하도록 수정.
- `BlogEntity`와 `UserEntity` 간의 관계 설정에서 발생하던 `TransientPropertyValueException` 문제를 해결.
- **목적**:
- 영속성 컨텍스트 내에서 안전하게 관계를 설정하여 예외 방지.
- **관련 이슈** : [#46](#)
---
- **변경 내용**:
- `블로그_ID로_연간_게시글_통계를_조회한다()` 테스트에서 잘못된 연도 값(2024)을 2025로 수정.
- **목적**:
- 최근 연간 게시글 통계 조회 테스트의 정확성을 보장.
- **관련 이슈** : [#45](#)
> 🚑 긴급 수정 : TransientPropertyValueException 해결, 테스트 연도 수정 및 초기 사용자 데이터 추가

- src/main/java/darkoverload/itzip/feature/jwt/filter/TokenAuthenticationFilter.java
> 🐛 오류 수정 - 올바르지 않은 토큰값 전송 시 서버 내부 에러가 반환되는 오류 수정

- src/main/java/darkoverload/itzip/feature/user/service/MypageServiceImpl.java
changeImageUrl 함수에서 user image url이 null인지 체크하는 구문 추가
Resolves: #206
> 🐛 오류 수정 - 최초 이미지 수정 시 발생하는 NullPointException 수정
